AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an EC2 instance using imported VPC and Subnet IDs from a network stack"

Parameters:
  CreateInstance:
    Description: "Set to true to create an EC2 instance, false to skip"
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"

  InstanceType:
    Description: "EC2 instance type"
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  Environment:
    Type: String
    Default: 'dev'
    Description: 'Environment for the resources'
    AllowedValues:
      - dev
      - prod
      - test
  KeyName:
    Description: "The name of an existing EC2 KeyPair"
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-02a53b0d62d37a757  # Example AMI for US East (N. Virginia)
    eu-west-1:
      AMI: ami-0a89fa9a6d8c7ad98  # Example AMI for EU West (Ireland)

Conditions:
  ShouldCreateInstance: !Equals [ !Ref CreateInstance, "true" ]

Resources:
  EffulgencetechEC2Instance:
    Type: AWS::EC2::Instance
    Condition: ShouldCreateInstance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue network-resource-EffulgencepubSubnet1 # Import from Network Stack
            
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo su 
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Welcome to My Web Server!</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: !Sub 'EffulgencetechEC2Instance-${Environment}' # Fn::Sub example
        - Key: Type
          Value: !Join ["-", ["EC2", "WebServer"]]  # Fn::Join example
        - Key: Environment
          Value: !Select [1, ["dev", "prod", "test"]]  # Fn::Select example
        - Key: Department
          Value: !Select [0, !Split [",", "IT,HR,Finance"]]  # Fn::Split example
Outputs:
  InstanceID:
    Description: "EC2 Instance ID"
    Value: !If [ShouldCreateInstance, !Ref EffulgencetechEC2Instance, "No instance created"]
  PublicDNS:
    Description: "Public DNS of the EC2 instance"
    Value: !If [ShouldCreateInstance, !GetAtt EffulgencetechEC2Instance.PublicDnsName, "No instance created"]
  PublicIP:
    Description: "Public IP of the EC2 instance"
    Value: !If [ShouldCreateInstance, !GetAtt EffulgencetechEC2Instance.PublicIp, "No instance created"]