AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

  EC2InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: Pekay-keys

  ImageId:
    Description: Image ID
    Type: AWS::EC2::Image::Id
    Default: ami-02a53b0d62d37a757

  Pub1SubnetId:
    Description: Public Subnet 1 ID
    Type: AWS::EC2::Subnet::Id

  Pub2SubnetId:
    Description: Public Subnet 2 ID
    Type: AWS::EC2::Subnet::Id

  Priv1SubnetId:
    Description: Private Subnet 1 ID
    Type: AWS::EC2::Subnet::Id

  Priv2SubnetId:
    Description: Private Subnet 2 ID
    Type: AWS::EC2::Subnet::Id

  WebServerSecurityGroup:
    Description: Security Group ID for Web Server
    Type: AWS::EC2::SecurityGroup::Id

  AppServerSecurityGroup:
    Description: Security Group ID for App Server
    Type: AWS::EC2::SecurityGroup::
  
Resources:
  WebserverEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      SubnetId: !Ref Pub1SubnetId
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: WebserverEC2
        - Key: Stack
          Value: production

  AppserverEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      SubnetId: !Ref Priv1SubnetId
      SecurityGroupIds:
        - !Ref AppServerSecurityGroup
      Tags:
        - Key: Name
          Value: AppserverEC2
        - Key: Stack
          Value: production

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ApplicationLoadBalancer
      Subnets:
        - !Ref Pub1SubnetId
        - !Ref Pub2SubnetId
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: ApplicationLB
        - Key: Stack
          Value: production

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: instance
      Tags:
        - Key: Name
          Value: TargetGroup
        - Key: Stack
          Value: production

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  WebserverEC2:
    Description: Webserver EC2 Instance ID
    Value: !Ref WebserverEC2
    Export:
      Name: !Sub "${AWS::StackName}-WebserverEC2"

  AppserverEC2:
    Description: Appserver EC2 Instance ID
    Value: !Ref AppserverEC2
    Export:
      Name: !Sub "${AWS::StackName}-AppserverEC2"

  ApplicationLoadBalancer:
    Description: Application Load Balancer ID
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub "${AWS::StackName}-ApplicationLoadBalancer"

  LoadBalancerDNSName:
    Description: Application Load Balancer DNS Name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-ApplicationLoadBalancerDNSName"
